# Generated by Django 4.1 on 2022-10-11 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorUser', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('subscribers', models.ManyToManyField(related_name='catigories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('description', models.TextField(verbose_name='Текст')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Заголовок')),
                ('author_new', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsproj.author', verbose_name='Автор')),
                ('category_new', models.ManyToManyField(to='newsproj.category', verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='NewCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsproj.category')),
                ('new', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsproj.new')),
            ],
        ),
    ]
